# Generated by Django 5.0.1 on 2024-03-26 02:37

import API.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('coverImage', models.ImageField(upload_to=API.models.artist_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], max_length=1)),
                ('description', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTitle', models.CharField(max_length=100)),
                ('releaseDate', models.DateTimeField(auto_now_add=True)),
                ('totalDuration', models.DurationField(blank=True, null=True)),
                ('numberOfSongs', models.PositiveIntegerField(blank=True, null=True)),
                ('coverImage', models.ImageField(upload_to=API.models.album_directory_path)),
                ('backGroundImage', models.ImageField(upload_to=API.models.album_directory_path)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcastTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('coverImage', models.ImageField(upload_to=API.models.podcast_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.podcastcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('episode', models.FileField(upload_to=API.models.episodes_directory_path)),
                ('releaseDate', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('audio', models.FileField(upload_to=API.models.songs_directory_path, validators=[API.models.Song.validate_mp3])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=100)),
                ('numberOfSongs', models.PositiveIntegerField(blank=True, null=True)),
                ('totalDuration', models.DurationField(blank=True, null=True)),
                ('coverImage', models.ImageField(upload_to=API.models.playlist_directory_path)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.library')),
                ('songs', models.ManyToManyField(blank=True, to='API.song')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPodcast', models.PositiveIntegerField(blank=True, null=True)),
                ('numberOfSongs', models.PositiveIntegerField(blank=True, null=True)),
                ('totalDuration', models.DurationField(blank=True, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.library')),
                ('podcasts', models.ManyToManyField(blank=True, to='API.podcast')),
                ('songs', models.ManyToManyField(blank=True, to='API.song')),
            ],
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('isActive', models.BooleanField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
