# Generated by Django 5.0.1 on 2024-04-01 22:47

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_podcast_owner_podcast_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='live',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(blank=True, null=True, upload_to=API.models.episodes_directory_path),
        ),
    ]
