# Generated by Django 5.0.1 on 2024-04-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
