# Generated by Django 5.0.1 on 2024-04-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_suscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, default="2024-04-06 12:00:00"),
            preserve_default=False,
        ),
    ]
