# Generated by Django 5.0.1 on 2024-04-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_suscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
