# Generated by Django 5.0.1 on 2024-04-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_suscription_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscription',
            name='isActive',
        ),
    ]
