# Generated by Django 5.0.1 on 2024-04-09 02:18

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_suscription_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=API.models.podcast_directory_path),
        ),
    ]
